stuff

diff --git a/lynxoff b/lynxoff
--- a/lynxoff
+++ b/lynxoff
@@ -35,12 +35,13 @@ while [[ $1 ]]; do
         echo -e "\nERROR: Unexpected parameter: \"$1\"";
         help;
         exit 1;
-    elif [[ $2 ]]; then
-        filename="$1";
-        shift;
-    else
+    elif [[ ! $url ]]; then
         url="$1";
         shift;
+    else
+        echo -e "\nERROR: Unexpected parameter: \"$1\"";
+        help;
+        exit 1;
     fi
 done
 
